on:
  workflow_call:
    inputs:
      terraform_version:
        type: string
        required: true
        description: The version of Terraform to use
      plan_artifact:
        type: string
        required: true
        description: The name of the artifact containing the plan file
      plan_file_name:
        type: string
        required: true
        description: The name of the plan file
      terraform_relative_dir:
        type: string
        default: .
        required: false
        description: The relative directory of the Terraform configuration
      data_branch_name:
        type: string
        default: inkdrop-ci-data
        required: false
        description: The name of the branch to store the Inkdrop images and CI data
      inkdrop_version:
        type: string
        default: latest
        required: false
        description: The version of Inkdrop to use (vX.Y.Z format)
      
      
jobs:
  run_inkdrop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}
          terraform_wrapper: false

      - name: Terraform
        working-directory: ${{ inputs.terraform_relative_dir }}
        run: |
          terraform init

      - name: Configure git
        run: |
          git config --global user.email "github-actions@example.com"
          git config --global user.name "GitHub Actions"  

      - name: Create Orphan Branch (if necessary)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking if '${{ inputs.data_branch_name }}' branch exists..."
          EXISTS=$(git ls-remote --heads origin ${{ inputs.data_branch_name }} | wc -l)
          if [ "$EXISTS" -eq "0" ]; then
            TEMP_DIR=$(mktemp -d)
            cd $TEMP_DIR
            git init
            git remote add origin ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git
            git config http.${GITHUB_SERVER_URL}/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.GITHUB_TOKEN }} | base64)"            
            touch README.md
            echo "### Branch used to store Inkdrop CI images and data" > README.md
            git add .
            git commit -m "Initial commit on orphan branch ${{ inputs.data_branch_name }}"
            
            git push --set-upstream origin master:refs/heads/${{ inputs.data_branch_name }}
            
            cd -
            rm -rf $TEMP_DIR
          else
            echo "'${{ inputs.data_branch_name }}' branch already exists."
          fi
          
      - name: Download and install Inkdrop
        run: |
          if [ "${{ inputs.inkdrop_version }}" = "latest" ]; then
            wget https://github.com/inkdrop-org/inkdrop-visualizer/releases/latest/download/inkdrop-linux-x64.tar.gz
          else
            wget https://github.com/inkdrop-org/inkdrop-visualizer/releases/download/${{ inputs.inkdrop_version }}/inkdrop-linux-x64.tar.gz
          fi
          tar -xzf inkdrop-linux-x64.tar.gz
          chmod +x inkdrop
          mv inkdrop /usr/local/bin/

      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.plan_artifact }}
          path: ${{ inputs.terraform_relative_dir }}

      - name: Run Inkdrop
        run: |
          inkdrop --ci ${{inputs.plan_file_name}}
        working-directory: ${{ inputs.terraform_relative_dir }}


      - name: Capture SVG File Name
        id: find_svg
        working-directory: ${{ inputs.terraform_relative_dir }}
        run: |
          SVG_FILE=$(ls -Art *.svg | tail -n 1)
          echo "Found SVG: $SVG_FILE"
          echo "::set-output name=svg_file_name::${SVG_FILE}"


      - name: Commit and push SVG and inkdrop-ci-data.json to inkdrop data branch
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const svgPath = process.env.SVG_FILE_PATH;
            const inkdropDataPath = process.env.INKDROP_DATA_PATH;
            const svgContent = fs.readFileSync(svgPath, { encoding: 'utf-8' });
            const inkdropDataContent = fs.readFileSync(inkdropDataPath, { encoding: 'utf-8' });
            const branch = '${{ inputs.data_branch_name }}';
            const svgName = svgPath.split('/').pop();
            const noExtensionSvgName = svgName.split('.svg')[0];
            const svgFilePath = `inkdrop-data/PR${process.env.PR_ID}/${svgPath.split('/').pop()}`;
            const inkdropDataFilePath = `inkdrop-data/PR${process.env.PR_ID}/${noExtensionSvgName}-${inkdropDataPath.split('/').pop()}`;

            // Encode content to Base64 for the GitHub API
            const contentBase64 = Buffer.from(svgContent).toString('base64');
            const inkdropDataContentBase64 = Buffer.from(inkdropDataContent).toString('base64');

            // Commit and push the file
            await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: svgFilePath,
                message: `Add SVG for PR ${process.env.PR_ID}`,
                content: contentBase64,
                branch,
            }).catch(error => core.setFailed(`Failed to commit SVG: ${error.message}`));

            await github.rest.repos.createOrUpdateFileContents({
                owner: context.repo.owner,
                repo: context.repo.repo,
                path: inkdropDataFilePath,
                message: `Add Inkdrop data JSON for PR ${process.env.PR_ID}`,
                content: inkdropDataContentBase64,
                branch,
            }).catch(error => core.setFailed(`Failed to commit Inkdrop data JSON: ${error.message}`));
        env:
          SVG_FILE_PATH: ${{ inputs.terraform_relative_dir }}/${{ steps.find_svg.outputs.svg_file_name }}
          INKDROP_DATA_PATH: ${{ inputs.terraform_relative_dir }}/inkdrop-ci-data.json
          PR_ID: ${{ github.event.pull_request.number }}

      - name: Comment PR with Inkdrop SVG Image Link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prId = ${{ github.event.pull_request.number }};
            const svgFileName = '${{ steps.find_svg.outputs.svg_file_name }}'.split('/').pop();
            const svgUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/blob/${{ inputs.data_branch_name }}/inkdrop-data/PR${prId}/${encodeURIComponent(svgFileName)}?raw=true`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prId,
              body: `### Inkdrop Diagram\n![Inkdrop Diagram SVG](${svgUrl})`
            });

      ################################# INKDROP DATA COMMENT ################################
      # The Inkdrop chrome extension needs this comment to render the interactive diagram.  #
      # By activating the extension, this comment will be hidden from the UI.               #
      # Don't manually change the following, or the chrome extension might stop working.    #
      #######################################################################################

      - name: Comment PR with Inkdrop CI JSON Data
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const prId = ${{ github.event.pull_request.number }};
            const inkdropDataFileName = '${{ steps.find_svg.outputs.svg_file_name }}'.split('.svg')[0] + '-' + process.env.INKDROP_DATA_NAME;
            const inkdropDataUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/blob/${{ inputs.data_branch_name }}/inkdrop-data/PR${prId}/${encodeURIComponent(inkdropDataFileName)}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prId,
              body: `Install the [Inkdrop Chrome Extension](https://chromewebstore.google.com/detail/visualize-your-terraform/pddpcicnnongifmhilbamagnhiiibkki) to hide this comment and enable interactive mode.\n### Inkdrop Data\n[Inkdrop Data JSON](${inkdropDataUrl})`
            });
        env:
          INKDROP_DATA_NAME: inkdrop-ci-data.json
