name: Build and Release for Linux and Alpine

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Get the version tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

  build_and_upload_linux:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Install dependencies
        run: npm install

      - name: Build Linux package
        run: |
          npm run build
          pkg -t node18-linux-x64 package.json -o release/inkdrop
          
      - name: Archive the Linux package
        run: tar -czvf release/inkdrop-linux-x64.tar.gz -C release inkdrop

      - name: Upload Linux package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./release/inkdrop-linux-x64.tar.gz
          asset_name: inkdrop-linux-x64.tar.gz
          asset_content_type: application/gzip

  build_and_upload_alpine:
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Install dependencies
        run: npm install

      - name: Build Alpine package
        run: |
          npm run build
          pkg -t node18-alpine-x64 package.json -o release/inkdrop
          
      - name: Archive the Alpine package
        run: tar -czvf release/inkdrop-alpine-x64.tar.gz -C release inkdrop

      - name: Upload Alpine package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./release/inkdrop-alpine-x64.tar.gz
          asset_name: inkdrop-alpine-x64.tar.gz
          asset_content_type: application/gzip
  
  build_and_upload_macos:
    needs: create_release
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pkg globally
        run: npm install -g pkg

      - name: Install dependencies
        run: npm install

      - name: Build MacOS package
        run: |
          npm run build
          pkg -t node18-macos-x64 package.json -o release/inkdrop

      - name: Archive the MacOS package
        run: tar -czvf release/inkdrop-macos-x64.tar.gz -C release inkdrop

      - name: Upload MacOS package to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./release/inkdrop-macos-x64.tar.gz
          asset_name: inkdrop-macos-x64.tar.gz
          asset_content_type: application/gzip

  update-homebrew:
    runs-on: ubuntu-latest
    needs: build_and_upload_macos
    steps:
      - name: Checkout Homebrew tap
        uses: actions/checkout@v4
        with:
          repository: inkdrop-org/homebrew-inkdrop-visualizer
          token: ${{ secrets.HOMEBREW_REPO_TOKEN }}

      - name: Download the macOS package
        run: |
          wget "https://github.com/inkdrop-org/terraform-visualizer-cli/releases/download/${GITHUB_REF#refs/tags/}/inkdrop-macos-x64.tar.gz" -O /tmp/inkdrop-macos-x64.tar.gz

      - name: Compute SHA256
        id: sha256
        run: echo "::set-output name=sha::$(sha256sum /tmp/inkdrop-macos-x64.tar.gz | awk '{print $1}')"

      - name: Update formula
        run: |
          FORMULA_PATH="${{ github.workspace }}/Formula/inkdrop-visualizer.rb"
          PACKAGE_URL="https://github.com/inkdrop-org/terraform-visualizer-cli/releases/download/${GITHUB_REF#refs/tags/}/inkdrop-macos-x64.tar.gz"
          SHA256="${{ steps.sha256.outputs.sha }}"
          VERSION="${GITHUB_REF#refs/tags/}"
          STRIPPED_VERSION="${VERSION#v}"
          sed -i "s|^  url .*|  url \"$PACKAGE_URL\"|" $FORMULA_PATH
          sed -i "s|^  sha256 .*|  sha256 \"$SHA256\"|" $FORMULA_PATH
          sed -i "s|^  version .*|  version \"$STRIPPED_VERSION\"|" $FORMULA_PATH

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/inkdrop-visualizer.rb
          git commit -m "Update inkdrop-visualizer to ${GITHUB_REF#refs/tags/}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_REPO_TOKEN }}